name: optimtech
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.10.12
  - scipy==1.11.4
  - numpy==1.25.2
  - matplotlib==3.7.1
  - pyscipopt==4.2.0
  - ipykernel
  - jupyterlab
  - pip
  - pip:
    - numdifftools==0.9.41
    - benchmark-functions==1.1.3
    - inspyred==1.0.1
    - cma==3.2.2
    - scikit-optimize==0.9.0
    - treed==2.1.0
    - rsome
    - gurobipy
    - notebook
 
